version: 2.0

jobs:
  build:
    working_directory: ~/dynamic-rest
    parallelism: 1

    docker:
      - image: circleci/python:2.7.16-stretch
    steps:
      - checkout
      - run:
          name: Update PATH variable
          command: echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ${BASH_ENV}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          context: org-global
